### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by GoelVaibhav009**

### CODE REVIEW

**Comment by GoelVaibhav009** [comment]
I have made few changes :- 
One in typo error in readme and another one is change Icon of app

**Review by Yashank18 — APPROVED** [review]
Great Work. I was thinking to clear all this clutter and you did it for me!
Thank you so much. 

Just a question are you using XCode to compile or Android SDK only?

**Comment by GoelVaibhav009** [comment]
Only Android SDK

**Comment by GoelVaibhav009** [comment]
Can i also update code more convenient to understand

**Comment by Yashank18** [comment]
@GoelVaibhav009 For now there is no need, we will be working on next version then will think of code clutter. 
Thank you for Helping.
Merging this :)

**Pull request merged**
