### PR TITLE
Added Splash Screen To app

### PR DESCRIPTION
**Pull request by GoelVaibhav009**

### CODE REVIEW

**Comment by Yashank18** [comment]
Hey @GoelVaibhav009 Can you please tell the moto of this PR

**Comment by GoelVaibhav009** [comment]
By giving SplashScreen app seems to be professional and we can use that time in loading the app content. Thats why i put SplashScreen to it.

**Comment by Yashank18** [comment]
Okay, can you please add a gif for the splash screen that you have added?

**Comment by GoelVaibhav009** [comment]
Pls send me the gif for it

**Comment by Yashank18** [comment]
Hey @GoelVaibhav009  actually i mean can you screen record and share what have you added on Splash screen. Just add that video/gif here in the comment

**Comment by GoelVaibhav009** [comment]
oh sorry, pls see https://drive.google.com/file/d/1c-Eivlwq1uLKVicA81LXeMEEAamd-Ka2/view?usp=sharing

**Comment by Yashank18** [comment]
@GoelVaibhav009 
Hey man i saw the Splash screen but we are not supposed to use DSC logo like that it is violating DSC guidelines.
For now i don't think we need a Splash screen as the app doesn't have that much data to load for the first page.

You can look around and maybe find some other bugs. For new feature i will suggest you to open new Issue first so that we can discuss it over there and then come to the implementation part. You have done great job in the PR but due to guidelines issue i wont be able to merge it.

I have a suggestion for you. We can make a file for contribution guidelines so that it will be easy for all to understand and take care of it. If interested create an issue and i will assign you and share all details.

Sorry but i will be closing this PR

**Comment by GoelVaibhav009** [comment]
Thanks for telling me about issues, I don't know about it because i am new to gitHub. Thanks

**Comment by Yashank18** [comment]
No issue :)

**Pull request closed without merging**
